In [10]:
import datetime

x = datetime.datetime(2025, 9, 15)
print(x)

today = datetime.date.today()

mahasiswa = ["Yeremia Suyanto", 2024071015, "Informatika", "DAA","Universitas Pembangunan Jaya", today]
print(mahasiswa)

2025-09-15 00:00:00
['Yeremia Suyanto', 2024071015, 'Informatika', 'DAA', 'Universitas Pembangunan Jaya', datetime.date(2025, 9, 15)]


In [49]:
print("NIM dan Prodi", mahasiswa[1:3])

NIM dan Prodi [2024071015, 'Informatika']


In [31]:
print("NIM:", mahasiswa[1])

NIM: 2024071015


In [32]:
mahasiswa[4]

'UPJ'

In [58]:
for xMahasiswa in mahasiswa:
    print(str(xMahasiswa) + " UPJ")

Yeremia Suyanto UPJ
2024071015 UPJ
Informatika UPJ
DAA UPJ
Universitas Pembangunan Jaya UPJ
2025-09-15 UPJ


In [63]:
UPJ = ["Universitas", "Pembangunan", "Jaya"]
print(" ".join(UPJ))

Universitas Pembangunan Jaya


In [61]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [65]:
nested_tuple = (100, (200,400,600),300,(400,800))
print(nested_tuple[1][1])

400


In [80]:
nama = {
    "Nama:": "Yeremia Suyanto",
    "NIM:": 2024071015,
    "Prodi:": "Informatika",
    "Universitas:": "Universitas Pembangunan Jaya"
}
print(nama)

{'Nama:': 'Yeremia Suyanto', 'NIM:': 2024071015, 'Prodi:': 'Informatika', 'Universitas:': 'Universitas Pembangunan Jaya'}


In [7]:
import pandas as pd

data = {
    'No': [1, 2, 3],
    'Prodi': ['Informatika', 'Sistem Informasi', 'Teknik Sipil'],
    'Mahasiswa': [50, 55, 40],
    'Laki-laki': [30, 30, 30],
    'Perempuan': [20, 25, 10],
}
df = pd.DataFrame(data)
print(df.to_string(index=False))

 No            Prodi  Mahasiswa  Laki-laki  Perempuan
  1      Informatika         50         30         20
  2 Sistem Informasi         55         30         25
  3     Teknik Sipil         40         30         10


In [8]:
import numpy as np

matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
